// write-ledger — write inputs.md, the hash ledger, from the extraction manifests.
//
// inputs.md is the one file the extraction side writes into the repository. It names no
// local path: the input sets live outside the repository, and the ledger fixes them by
// hash before the answer key exists (README, "Protocol").
//
// It plans by default (printing the ledger) and writes nothing without --apply.

import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { EXIT, ROUNDS, SPIKE_DIR, UsageError, assembleRubric, main, pathExists, sha256 } from './lib.mjs';

const USAGE = `
write-ledger — write inputs.md from the extraction manifests.

  node src/write-ledger.mjs --rubric-parts <dir>                      print the ledger
  node src/write-ledger.mjs --rubric-parts <dir> --apply [--replace]  write inputs.md

Options
  --work <dir>            the extraction's --work folder (default: <tmp>/vcb/work)
  --rubric-parts <dir>    the rubric's transport pieces and ORDER.txt
  --rubric-extra <file>   a rubric transport file kept but not assembled; repeatable
  --apply                 actually write inputs.md
  --replace               overwrite an existing inputs.md
  --help                  show this message

Exit codes: 0 success/plan · 1 failed · 2 bad usage
`.trimStart();

await main(async () => {
  let values;
  try {
    ({ values } = parseArgs({
      options: {
        work: { type: 'string' },
        'rubric-parts': { type: 'string' },
        'rubric-extra': { type: 'string', multiple: true, default: [] },
        apply: { type: 'boolean', default: false },
        replace: { type: 'boolean', default: false },
        help: { type: 'boolean', default: false },
      },
    }));
  } catch (err) {
    throw new UsageError(`${err.message}\n\n${USAGE}`);
  }
  if (values.help) {
    console.log(USAGE);
    return EXIT.OK;
  }
  if (!values['rubric-parts']) throw new UsageError(`--rubric-parts is required\n\n${USAGE}`);

  const work = path.resolve(values.work ?? path.join(os.tmpdir(), 'vcb', 'work'));
  const manifests = [];
  for (const round of ROUNDS) {
    const file = path.join(work, round.id, 'manifest.json');
    if (await pathExists(file)) manifests.push(JSON.parse(await fs.readFile(file, 'utf8')));
  }
  if (!manifests.length) throw new UsageError(`no round manifests under ${work}; run extract-inputs.mjs --apply first`);

  const text = [header(), environment(manifests), await rubricSection(values), ...manifests.map(roundSection)].join('\n');
  const dest = path.join(SPIKE_DIR, 'inputs.md');
  if (!values.apply) {
    console.log(text);
    console.log(`\nplan only — would write ${dest}. Re-run with --apply.`);
    return EXIT.OK;
  }
  if ((await pathExists(dest)) && !values.replace) throw new UsageError(`${dest} exists; pass --replace to overwrite it`);
  await fs.writeFile(dest, text);
  console.log(`wrote ${dest} (rounds: ${manifests.map((m) => m.round).join(', ')})`);
  return EXIT.OK;
});

// Helpers are function declarations: the top-level await above runs before any const
// below it is initialised.
function code(s) {
  return s == null ? '—' : `\`${s}\``;
}

function table(head, rows) {
  return [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
}

function header() {
  return `# Inputs ledger

Written by \`src/write-ledger.mjs\` from the manifests \`src/extract-inputs.mjs\` leaves
beside each round's build. Do not edit it by hand; re-run the extraction and the ledger.

The files named here are kept outside the repository (README, "What git holds"). Paths
are relative to the extraction's output folder. A coach run reads exactly one of
\`<round>/pass1/\` or \`<round>/pass2/\`, plus \`rubric.md\`.

Git blob ids identify committed files. A file with no blob id was generated by the
extraction, and its SHA-256 is the only record of it.
`;
}

function environment(manifests) {
  const keys = ['node', 'npm', 'git', 'platform'];
  const first = manifests[0].tools;
  const differs = manifests.filter((m) => keys.some((k) => m.tools[k] !== first[k])).map((m) => m.round);
  if (differs.length) throw new Error(`rounds were extracted with different tools: ${differs.join(', ')}; re-extract them together`);
  return `## Environment

${table(['Tool', 'Version'], keys.map((k) => [k, code(first[k])]))}
`;
}

async function rubricSection(values) {
  const rubric = await assembleRubric(path.resolve(values['rubric-parts']));
  if (rubric.duplicates.length) throw new Error(`rubric has duplicate rule ids: ${rubric.duplicates.join(' ')}`);
  const file = path.join(SPIKE_DIR, 'rubric.md');
  if (!(await pathExists(file))) throw new Error('rubric.md does not exist; run assemble-rubric.mjs --apply first');
  const onDisk = await fs.readFile(file);
  const reproduces = onDisk.equals(Buffer.from(rubric.text, 'utf8'));
  if (!reproduces) throw new Error('rubric.md does not match its pieces; re-run assemble-rubric.mjs');

  const extras = [];
  for (const f of values['rubric-extra']) {
    const buf = await fs.readFile(path.resolve(f));
    extras.push([code(path.basename(f)), buf.length, code(sha256(buf))]);
  }
  const disclosures = rubric.pieces.flatMap((p) => p.removed.filter((l) => /^REGENERATED: /.test(l.trim())).map((l) => `- \`${p.name}\`: ${l.trim()}`));
  const briefFile = path.join(SPIKE_DIR, 'rubric-brief.md');
  if (!(await pathExists(briefFile))) throw new Error('rubric-brief.md does not exist');
  const brief = await fs.readFile(briefFile);
  return `## Rubric

\`rubric-brief.md\`: ${brief.length} bytes, SHA-256 ${code(sha256(brief))}. The rubric author's dispatch
prompt, verbatim.

\`rubric.md\`: ${onDisk.length} bytes, SHA-256 ${code(sha256(onDisk))}, ${rubric.ids.length} rules
(${rubric.ids.join(', ')}).

Joining the pieces below in this order, with transport lines removed, reproduces
\`rubric.md\` byte for byte. The ledger checks this each time it is written.

${table(['#', 'Piece', 'Bytes', 'SHA-256', 'Joined by'], rubric.pieces.map((p, i) => [i + 1, code(p.name), p.bytes, code(p.sha256), p.join]))}

A piece's name is the line of the session event log it was recovered from.

The author's disclosures, which travelled as transport lines and are not in \`rubric.md\`:

${disclosures.join('\n')}
${extras.length ? `\nKept, not assembled:\n\n${table(['File', 'Bytes', 'SHA-256'], extras)}\n` : ''}`;
}

function roundSection(m) {
  const pf = m.preFix;
  const ck = m.checkpoint;
  const diff = (c) => c.files.filter((f) => !f.same).map((f) => path.posix.basename(f.path));
  const nextLine = ck.next?.commit
    ? `Checkpoint #${ck.next.index} (${code(ck.next.commit)}) differs from the pre-fix state in: ${diff(ck.next).join(', ') || 'nothing'}.`
    : `Checkpoint #${ck.next?.index} does not exist.`;
  return `## Round ${m.round} (${m.kind})

- **Pre-fix state:** ${code(m.commit)}.
- **Pre-fix rule:** the first commit after it on ${code(m.lineage.ref)} (tip ${code(m.lineage.tip)}) that
  changes an input file is ${code(pf.firstFix)}, "${pf.firstFixSubject}". The last commit before that one
  to change an input file is ${code(pf.lastInputCommitBeforeFix)}: the rule **${pf.holds ? 'holds' : 'does not hold'}**.
- **Export:** ${m.export.files} files under ${m.export.roots.map(code).join(' and ')}, written from git's object
  store. ${m.export.verified} of ${m.export.files} re-hash to their blob ids.
- **Browser:** playwright ${code(m.tools.playwright)}, chromium ${code(m.tools.chromium)}, headless shell ${code(m.tools.headlessShell)}.
- **Layout audit:** ${m.layoutAudit}. **End card:** ${m.endCard}.

${table(['Engine file', 'Blob'], Object.entries(m.engine).map(([p, b]) => [code(p), code(b)]))}

${table(['Stage', 'Command', 'Exit'], m.stages.map((s) => [s.label, code(s.command), s.exitCode]))}

**Checkpoint cross-check.** Checkpoint #${ck.index} (${code(ck.commit)}):

${table(['File', 'Pre-fix blob', 'Checkpoint blob', 'Same'], ck.files.map((f) => [code(f.path), code(f.preFix), code(f.checkpoint), f.same ? 'yes' : '**no**']))}

${nextLine}

**Files.**

${table(['Pass', 'File', 'Git blob', 'SHA-256', 'Bytes', 'Note'], m.files.map((f) => [f.pass, code(`${m.round}/${f.file}`), code(f.blob), code(f.sha256), f.bytes, f.width ? `${f.width}×${f.height}` : (f.generated ?? '')]))}
`;
}
