/*
 * Whether the music gain about to be applied is one somebody actually agreed to.
 *
 * ## What this records, and what it does NOT
 *
 * THIS PIN RECORDS A CONFIRMATION, NOT A MEASUREMENT. That distinction is the whole
 * reason this module exists, and stating it here is not decoration — the previous
 * version of this check conflated the two and reproduced the bug it was built to stop.
 *
 * Bug-ledger entry 16: a bed generated by make-music.mjs measured -43.1 dB RMS, a
 * licensed master measured -11.4 dB — 31.7 dB apart — and the unchanged gain shipped the
 * bed about 10 dB hot. Every narration-silent-window check stayed green, because those
 * measure whether a bed is PRESENT, not whether it is at the right LEVEL.
 *
 * The first fix pinned the gain to a SHA-256 of the music source and asked only whether
 * that hash had CHANGED. Its author's own words on handing it back:
 *
 *     "I checked whether the input changed and called it proof the gain was calibrated —
 *      the same conflation, one level up."
 *
 * A changed input is evidence that a calibration is STALE. It is not evidence that any
 * calibration ever happened. Those are different claims and the check made the stronger
 * one, which left three ways to reach the mix with a gain nobody had confirmed:
 *
 *   1. a FIRST run had no lock to compare against, so it passed and pinned its own
 *      default — minting a calibration record for a gain no one had ever looked at;
 *   2. a changed --music-gain against an UNCHANGED source was never questioned, even
 *      though the multiplier moving lands in the same place as the source moving;
 *   3. --confirm-gain was read as a blanket "yes" rather than an answer to a question.
 *
 * ## Why this is a confirmation and not a measurement
 *
 * A measured pin would record the bed's resulting level and refuse when it drifted. That
 * is the right design and it is NOT buildable from what exists today:
 *
 *   - check-levels.mjs writes NOTHING. It prints to stdout and exits; there is no
 *     artifact for this to consume.
 *   - what it measures is a RENDERED VIDEO, not the music source, and it has no notion
 *     of which music file or gain produced what it measured — so nothing it produces can
 *     be bound to the source hash being pinned here.
 *   - the render being measured does not exist until after the remux this pin guards.
 *
 * So the honest contract is the narrower one: a human was ASKED, and said yes to this
 * gain for this source. The lock records `evidence: "operator-confirmed"` so that a
 * later reader cannot mistake it for a measured level. Closing that gap properly means
 * remux-music taking its own astats reading of the source and recording
 * `sourceRms + 20*log10(gain)` as the predicted bed level — a real measurement, and a
 * larger change that trades directly against keeping the plan path cheap. It is named
 * in the README as a known gap rather than papered over here.
 *
 * ## What the pin covers, and why that is no longer a literal
 *
 * A fourth way through was open until recently, and it was structural rather than
 * accidental. This pin recorded `{ source, sha256, musicGain }` — a hand-written set,
 * fixed at the moment it was typed. `--ceiling` was added afterwards; it clamps the
 * finished mix, so it moves the delivered loudness, and the pin had never heard of it. A
 * ceiling change therefore needed no renewed confirmation while the mix moved underneath
 * a pin reporting itself valid.
 *
 * The enumeration was not the mistake. The mistake was that the set was CLOSED BY
 * CONSTRUCTION and nothing failed when it grew. So the pin no longer names its members:
 * it binds to the `pinned` subset of MIX_PARAMETERS (mix-parameters.mjs), which is also
 * the set the mix graph is built from and audited against. Declaring a knob there covers
 * it here, and a knob that reaches the graph undeclared stops the run.
 *
 * Read the limits section of mix-parameters.mjs before trusting that further than it
 * goes. In particular, nothing mechanical decides whether `pinned` is set correctly.
 */
import { MIX_PARAMETERS, isMixRecord } from "./mix-parameters.mjs";

const SHA256 = /^[0-9a-f]{64}$/i;

/** The registry members whose movement invalidates a confirmation. */
const PINNED_PARAMETERS = MIX_PARAMETERS.filter(
  (parameter) => parameter.pinned,
);

/**
 * The only evidence kind this pin trusts.
 *
 * A lock is a claim about who agreed to something. This marker is written ONLY on a run
 * where an operator actually passed --confirm-gain, so its absence means no confirmation
 * is recorded — whatever wrote the file. That is the difference between "an operator
 * confirmed this" and a file that merely carries values, and a pin that does not say
 * which one it is does not get read as the stronger one.
 *
 * What the absence does NOT establish is WHO wrote the file or WHEN. Earlier versions of
 * this pin did write their own defaults without asking anybody, and such files exist; so
 * do hand-edited and truncated ones. The refusal text names the missing marker and stops
 * there, because that is the whole of what the file proves.
 */
const OPERATOR_CONFIRMED = "operator-confirmed";

/** A pinned digest, or null when the lock does not carry a readable one. */
function readPinnedSha(lock) {
  return typeof lock?.sha256 === "string" && SHA256.test(lock.sha256)
    ? lock.sha256.toLowerCase()
    : null;
}

/**
 * Whether this lock is COMPLETE IN THE SHAPE THE PIN USED TO WRITE: `{source, sha256,
 * musicGain}`.
 *
 * "This pin predates the registry" is a claim about WHEN A FILE WAS WRITTEN, and the
 * only thing on disk that supports it is the old shape itself. A lock carrying nothing
 * but a digest is missing `source` and `musicGain` too, so it is not the old shape — it
 * is a file that records no mix parameters, and saying more than that invents a history.
 *
 * That distinction is not pedantry. This module has already shipped the stronger-claim
 * mistake once, when collapsing staleness and provenance let a stale pin describe itself
 * as confirmed against a source nobody agreed to. A refusal may name what is missing
 * without naming who left it out.
 */
function isPreRegistryShape(lock) {
  return (
    typeof lock?.source === "string" &&
    lock.source.length > 0 &&
    typeof lock?.musicGain === "number" &&
    Number.isFinite(lock.musicGain)
  );
}

/**
 * Decides whether these mix parameters, for this source, have been confirmed.
 *
 * Three things must hold, and the third is the one that was missing: the source matches,
 * every PINNED mix parameter matches, AND the pin records an actual operator
 * confirmation. Checking only the first two reads a self-pinned legacy lock as confirmed,
 * and a successful run then rewrites it carrying `evidence: "operator-confirmed"` —
 * laundering a record into provenance it never had, and producing a file that looks
 * STRONGER than its source. Putting the distinction in the artifact and not in the
 * predicate is the same class of error as the rest of this audit: it exists in the file
 * and not in the decision.
 *
 * A lock whose fields cannot be read is NOT treated as a match either. Defaulting an
 * unreadable pin to "fine" would produce the evidence of a check with none of the
 * protection — a truncated or hand-edited lock would wave any gain through.
 *
 * FIVE REFUSAL STATES ARE KEPT APART, because each sends the reader somewhere different
 * and collapsing them is what let a stale pin describe itself as confirmed:
 *   - `unreadablePin`   the file is there but cannot be read as a pin;
 *   - `preRegistryPin`  it records no mix set, AND it carries the complete shape this pin
 *                       used to write (`source` + `musicGain`), which is the only thing
 *                       on disk that supports dating it. Refused, never back-filled:
 *                       inventing the missing values would mint an agreement nobody gave;
 *   - `noMixRecord`     it records no mix set and is not that shape either. Refused, and
 *                       described by WHAT IS MISSING — nothing about it establishes when
 *                       it was written or what produced it, so the refusal does not say;
 *   - `unrecordedParameters` it records a mix set that is missing a registered member;
 *   - `changedParameters`    it records the member, and the member moved.
 *
 * The split between the middle two is the same discipline as the staleness/provenance
 * split above, one level down: a refusal may name what is missing without inventing who
 * left it out or when.
 *
 * @param {object|null} lock the parsed lock file, or null when there is none
 * @param {{source: string, sha256: string, mix: Record<string, number>}} current what is being applied now
 * @returns {{first: boolean, unreadablePin: boolean, preRegistryPin: boolean, noMixRecord: boolean,
 *            unconfirmedPin: boolean, pinRecordsConfirmation: boolean, sourceChanged: boolean,
 *            changedParameters: Array<{name: string, flag: string, summary: string, was: number, now: number}>,
 *            unrecordedParameters: Array<{name: string, flag: string, summary: string, now: number}>,
 *            requiresConfirmation: boolean, pinnedSha: string|null}}
 */
export function classifyGainPin(lock, current) {
  const first =
    lock === null ||
    lock === undefined ||
    typeof lock !== "object" ||
    Array.isArray(lock);

  const pinnedSha = first ? null : readPinnedSha(lock);
  const record = first ? undefined : lock.mix;
  const mixAbsent = record === undefined;

  // A missing mix record and a malformed one are different diagnoses. `mix: null` or
  // `mix: "x"` means someone wrote something unreadable; no `mix` key at all means the
  // file records no mix parameters.
  //
  // WHY THAT SPLITS IN TWO. A lock with no `mix` and the complete old shape around it is
  // evidence of a pin written before the registry — a legitimate history. A lock with no
  // `mix` AND no `source` AND no `musicGain` is evidence of nothing but its own silence.
  // Both are refused; only the first may be dated.
  const unreadablePin =
    !first && (pinnedSha === null || (!mixAbsent && !isMixRecord(record)));
  const preRegistryPin =
    !first && !unreadablePin && mixAbsent && isPreRegistryShape(lock);
  const noMixRecord = !first && !unreadablePin && mixAbsent && !preRegistryPin;

  const sourceChanged =
    pinnedSha !== null && pinnedSha !== String(current.sha256).toLowerCase();

  const currentMix = isMixRecord(current?.mix) ? current.mix : {};
  const changedParameters = [];
  const unrecordedParameters = [];
  if (!first && !unreadablePin && !preRegistryPin && !noMixRecord) {
    for (const { name, flag, summary } of PINNED_PARAMETERS) {
      const was = record[name];
      const now = currentMix[name];
      // Absent or unreadable is NOT "unchanged": a pin that does not record a member
      // cannot certify it, and reading a missing field as a match is the permissive
      // default this whole check exists to refuse.
      if (typeof was !== "number" || !Number.isFinite(was))
        unrecordedParameters.push({ name, flag, summary, now });
      else if (was !== now)
        changedParameters.push({ name, flag, summary, was, now });
    }
  }

  const stale =
    sourceChanged ||
    changedParameters.length > 0 ||
    unrecordedParameters.length > 0;

  // Whether the EXISTING pin was ever agreed to, asked independently of whether it is
  // stale. Staleness and provenance are different questions, and collapsing them is what
  // let a refusal describe a legacy pin as "confirmed against" — asserting an agreement
  // that never happened, inside the one feature built to stop exactly that.
  const pinRecordsConfirmation = !first && lock.evidence === OPERATOR_CONFIRMED;

  // Only asked once the pin is otherwise readable and matching: "this lock records no
  // confirmation" is the right diagnosis for a pin that carries the values and no
  // agreement, and the wrong one for a pin that is simply stale.
  const unconfirmedPin =
    !first &&
    !unreadablePin &&
    !preRegistryPin &&
    !noMixRecord &&
    !stale &&
    !pinRecordsConfirmation;

  return {
    first,
    unreadablePin,
    preRegistryPin,
    noMixRecord,
    unconfirmedPin,
    pinRecordsConfirmation,
    sourceChanged,
    changedParameters,
    unrecordedParameters,
    requiresConfirmation:
      first ||
      unreadablePin ||
      preRegistryPin ||
      noMixRecord ||
      unconfirmedPin ||
      stale,
    pinnedSha,
  };
}

const WHY_PRESENCE_IS_NOT_LEVEL =
  "A gain is only meaningful for the track it was confirmed against; two tracks can sit\n" +
  "30 dB apart and both accept the same in-range gain. The narration-gap checks cannot\n" +
  "see this — they measure whether a bed is present, not whether it is at the right level.";

/*
 * THE MEASUREMENT COMES AFTER, AND THE INSTRUCTION HAS TO SAY SO.
 *
 * The first version of this text told the operator to measure the result with
 * check-levels.mjs and THEN re-run with --confirm-gain. That cannot be done: the result
 * it names is the mix this very run would have produced, and the refusal is what stopped
 * it being produced. The circularity was documented in the README while the text a person
 * actually reads still asked for the impossible order.
 *
 * check-levels.mjs measures a RENDERED FILE. So the honest sequence is confirm, render,
 * measure, and only then deliver — and --confirm-gain has to be described as what it is,
 * an acceptance recorded in advance, not a measurement that has already happened.
 *
 * THOSE TWO SENTENCES USED TO CONTRADICT EACH OTHER. This block said there was nothing to
 * measure yet and then called the flag an assertion that a person MEASURED the mix. On the
 * run where the flag is mandatory — the first — no mix exists, so nothing can have been
 * measured. The flag records an ACCEPTANCE whose evidential basis varies and which this
 * tool cannot verify at all; saying so is the only version that is true on both runs.
 * `remux-music.mjs`'s help and the README's gain-pin section state the same claim, and a
 * test pins the pairing so the three cannot drift back apart.
 */
const HOW_TO_PROCEED =
  "There is nothing to measure yet: the bed level can only be read off a finished mix,\n" +
  "and that mix is what this run would have produced. So the order is:\n" +
  "\n" +
  "  1. re-run with --confirm-gain — this records a PROVISIONAL acceptance of these mix\n" +
  "     parameters for this source, and produces the mix;\n" +
  "  2. measure that output before you deliver it:\n" +
  "       node src/check-levels.mjs --file <your --out file>\n" +
  "  3. read the lead-in window, where the bed plays alone. If the level is wrong, re-run\n" +
  "     step 1 with corrected values; the pin will ask again because they moved.\n" +
  "\n" +
  "--confirm-gain is the caller's assertion that a person has accepted these values for\n" +
  "this source — having measured or listened to a mix where one exists, and provisionally\n" +
  "where none does yet, as on this run. The tool can verify neither, and it records\n" +
  `"${OPERATOR_CONFIRMED}" either way. An agent must not pass it on its own\n` +
  "authority: ask the person, and pass it only on their answer. What the pin records is\n" +
  "that acceptance, not a measurement of the result — this tool cannot measure that for\n" +
  "you. See the gain-pin section of the README for why, and for what closing that gap\n" +
  "properly would take.";

/**
 * The record a confirmed run writes: the one shape `classifyGainPin` reads back as settled.
 *
 * Pure, and kept beside the classifier rather than inline in remux-music's writer, so a
 * test can round-trip the record that is actually written instead of one it built itself.
 */
export function confirmedLockRecord(current, confirmedAt) {
  return { ...current, evidence: OPERATOR_CONFIRMED, confirmedAt };
}

/**
 * The refusal text for an unconfirmed mix, naming every cause separately.
 *
 * Each branch names both sides of what it compared. "Something changed" sends the reader
 * looking; "--ceiling 1 became 2, against the same track" tells them what to check. When
 * more than one thing moved, each gets its own line: collapsing a ceiling change into
 * "the source changed" describes a cause that did not occur, and a reader who follows
 * that text reasons from a history that does not exist.
 */
export function describeGainPinRefusal(verdict, current) {
  const short = (sha) => String(sha).slice(0, 12);
  const applying = () =>
    PINNED_PARAMETERS.map(
      ({ name, flag }) => `${flag} ${current.mix?.[name]}`,
    ).join(", ");

  // How the EXISTING pin may honestly be described. A stale pin and an unconfirmed one
  // are independent, so the staleness branches below must not borrow the word "confirmed"
  // from a record that never carried it.
  const held = verdict.pinRecordsConfirmation
    ? "confirmed against"
    : "pinned, NEVER CONFIRMED, against";
  const noConfirmationNote = verdict.pinRecordsConfirmation
    ? ""
    : "\nThe pin it is being compared against records no confirmation either — the marker\n" +
      "this tool writes when someone passes --confirm-gain is absent from it. What wrote\n" +
      "that file cannot be told from its contents and is not guessed at here; what can be\n" +
      "said is that neither the old values nor the new ones carry an agreement.";

  /*
   * THE SECOND, INDEPENDENT DIFFERENCE — which the pre-registry refusal used to omit.
   *
   * A pin can both fail to record the mix AND be pinned to a different track. Those are
   * separate facts with separate fixes, and naming only the first sent an operator to
   * re-confirm against a source they had not been told had moved. They found out on the
   * next run.
   *
   * Reporting it is not the same as calling the old values confirmed: it states that two
   * readable digests differ, which is the whole of what is known.
   */
  const digestAlsoDiffers = () =>
    verdict.sourceChanged
      ? "\nThe digest it does carry is ALSO not the one being supplied — a second and entirely\n" +
        "independent difference, so re-confirming will be answering for a different track too:\n" +
        `      pinned digest  ${short(verdict.pinnedSha)}\n` +
        `      now supplied   ${current.source} (${short(current.sha256)})`
      : "";

  const head = (() => {
    if (verdict.first) {
      return (
        `the mix parameters about to be applied have NEVER BEEN CONFIRMED for ${current.source} ` +
        `(${short(current.sha256)}):\n  ${applying()}\n` +
        "There is no pin to check them against, so nothing here has established that this\n" +
        "bed level is right for this track — and pinning it now would record a confirmation\n" +
        "that never happened."
      );
    }
    if (verdict.unreadablePin) {
      return (
        "the music gain pin exists but cannot be read as a pin — its source digest or its\n" +
        "record of the mix parameters is missing or malformed. An unreadable pin is not a\n" +
        "confirmation, and it is not treated as one."
      );
    }
    if (verdict.preRegistryPin) {
      return (
        `the music gain pin PREDATES the registered set of mix parameters, so it cannot say\n` +
        `which ${PINNED_PARAMETERS.map((p) => p.flag).join(", ")} it covered.\n` +
        "It carries the shape the pin used to write — the music gain alone. The narration\n" +
        "gain and the limiter ceiling also move the delivered loudness, and a pin that is\n" +
        "silent about them certifies nothing about the mix now being asked for. Back-filling\n" +
        "today's values would be worse than refusing: it would record an agreement nobody\n" +
        "was asked for.\n" +
        `  now asking  ${applying()}` +
        digestAlsoDiffers() +
        "\nEvery pin written before this change needs one fresh confirmation. That is the cost,\n" +
        "and it is paid once per project."
      );
    }
    if (verdict.noMixRecord) {
      return (
        "the music gain pin RECORDS NO MIX PARAMETERS. It carries a readable source digest\n" +
        `and nothing that says which ${PINNED_PARAMETERS.map((p) => p.flag).join(", ")} it covered.\n` +
        "It is not the shape this pin used to write either, so nothing about it establishes\n" +
        "when it was written or what produced it, and this refusal does not guess. What is\n" +
        "certain is that it cannot certify the mix now being asked for, and inventing the\n" +
        "missing values would mint an agreement nobody gave.\n" +
        `  now asking  ${applying()}` +
        digestAlsoDiffers() +
        "\nRe-run with --confirm-gain to replace it with a pin that records the whole set."
      );
    }
    if (verdict.unconfirmedPin) {
      return (
        `the music gain pin matches ${current.source} (${short(current.sha256)}) on every registered\n` +
        "mix parameter, but it RECORDS NO CONFIRMATION.\n" +
        "The marker this tool writes when someone passes --confirm-gain is absent. What\n" +
        "produced the file cannot be told from its contents and is not guessed at here — so\n" +
        "the values agreeing establishes only that they have not moved since it was written,\n" +
        "not that anybody ever agreed to them. Matching a record that carries no\n" +
        "confirmation is not evidence that a confirmation happened.\n" +
        "Re-confirming an old pin costs one flag; trusting one costs a delivered mix."
      );
    }

    // STALE. Every cause gets its own line, with its own before and after.
    const causes = [];
    if (verdict.sourceChanged) {
      causes.push(
        "  - the music source CHANGED\n" +
          `      now supplied  ${current.source} (${short(current.sha256)})`,
      );
    }
    for (const { flag, summary, was, now } of verdict.changedParameters) {
      causes.push(
        `  - ${flag} CHANGED — ${summary}\n` +
          `      confirmed  ${was}\n` +
          `      now asked  ${now}`,
      );
    }
    for (const { flag, summary, now } of verdict.unrecordedParameters) {
      causes.push(
        `  - the pin DOES NOT RECORD ${flag} — ${summary}\n` +
          `      now asked  ${now}`,
      );
    }
    return (
      "the confirmation on record does not cover the mix about to be produced.\n" +
      `  ${held}  ${short(verdict.pinnedSha)}\n` +
      `${causes.join("\n")}` +
      noConfirmationNote
    );
  })();

  return `${head}\n\n${WHY_PRESENCE_IS_NOT_LEVEL}\n\n${HOW_TO_PROCEED}`;
}

/**
 * The one-line pin status for the plan.
 *
 * The plan writes nothing, so it does not refuse — but it must not read as though the
 * mix were settled when --apply is going to stop. It says which way it will go, and
 * which knob is responsible.
 */
export function describeGainPinPlan(verdict, current, confirmed) {
  const short = String(current.sha256).slice(0, 12);
  const applying = PINNED_PARAMETERS.map(
    ({ name, flag }) => `${flag} ${current.mix?.[name]}`,
  ).join(", ");
  if (!verdict.requiresConfirmation)
    return `confirmed for ${current.source} (${short}) at ${applying}`;
  // A pin can fail to record the mix AND be pinned to a different track. The plan names
  // both, for the same reason the refusal does: one of them is a surprise on the next run.
  const alsoMoved = verdict.sourceChanged ? ", source changed" : "";
  const why = verdict.first
    ? "never confirmed"
    : verdict.unreadablePin
      ? "pin unreadable"
      : verdict.preRegistryPin
        ? `pin predates the registered mix parameters${alsoMoved}`
        : verdict.noMixRecord
          ? `pin records no mix parameters${alsoMoved}`
          : verdict.unconfirmedPin
            ? "pin records no confirmation"
            : [
                ...(verdict.sourceChanged ? ["source changed"] : []),
                ...verdict.changedParameters.map(
                  ({ flag }) => `${flag} changed`,
                ),
                ...verdict.unrecordedParameters.map(
                  ({ flag }) => `pin does not record ${flag}`,
                ),
              ].join(", ");
  return confirmed
    ? `${why} — will be RE-PINNED to ${short} at ${applying} (--confirm-gain given)`
    : `${why} — --apply will REFUSE until --confirm-gain is given`;
}
