/*
 * Whether the music gain about to be applied is one somebody actually agreed to.
 *
 * ## What this records, and what it does NOT
 *
 * THIS PIN RECORDS A CONFIRMATION, NOT A MEASUREMENT. That distinction is the whole
 * reason this module exists, and stating it here is not decoration — the previous
 * version of this check conflated the two and reproduced the bug it was built to stop.
 *
 * Bug-ledger entry 16: a bed generated by make-music.mjs measured -43.1 dB RMS, a
 * licensed master measured -11.4 dB — 31.7 dB apart — and the unchanged gain shipped the
 * bed about 10 dB hot. Every narration-silent-window check stayed green, because those
 * measure whether a bed is PRESENT, not whether it is at the right LEVEL.
 *
 * The first fix pinned the gain to a SHA-256 of the music source and asked only whether
 * that hash had CHANGED. Its author's own words on handing it back:
 *
 *     "I checked whether the input changed and called it proof the gain was calibrated —
 *      the same conflation, one level up."
 *
 * A changed input is evidence that a calibration is STALE. It is not evidence that any
 * calibration ever happened. Those are different claims and the check made the stronger
 * one, which left three ways to reach the mix with a gain nobody had confirmed:
 *
 *   1. a FIRST run had no lock to compare against, so it passed and pinned its own
 *      default — minting a calibration record for a gain no one had ever looked at;
 *   2. a changed --music-gain against an UNCHANGED source was never questioned, even
 *      though the multiplier moving lands in the same place as the source moving;
 *   3. --confirm-gain was read as a blanket "yes" rather than an answer to a question.
 *
 * ## Why this is a confirmation and not a measurement
 *
 * A measured pin would record the bed's resulting level and refuse when it drifted. That
 * is the right design and it is NOT buildable from what exists today:
 *
 *   - check-levels.mjs writes NOTHING. It prints to stdout and exits; there is no
 *     artifact for this to consume.
 *   - what it measures is a RENDERED VIDEO, not the music source, and it has no notion
 *     of which music file or gain produced what it measured — so nothing it produces can
 *     be bound to the source hash being pinned here.
 *   - the render being measured does not exist until after the remux this pin guards.
 *
 * So the honest contract is the narrower one: a human was ASKED, and said yes to this
 * gain for this source. The lock records `evidence: "operator-confirmed"` so that a
 * later reader cannot mistake it for a measured level. Closing that gap properly means
 * remux-music taking its own astats reading of the source and recording
 * `sourceRms + 20*log10(gain)` as the predicted bed level — a real measurement, and a
 * larger change that trades directly against keeping the plan path cheap. It is named
 * in the README as a known gap rather than papered over here.
 */

const SHA256 = /^[0-9a-f]{64}$/i;

/**
 * The only evidence kind this pin trusts.
 *
 * A lock is a claim about who agreed to something. `music-gain.lock.json` predates this
 * field, and those older files were written by code that pinned its own default without
 * asking anybody — so the absence of this marker is not a formatting detail, it is the
 * difference between "an operator confirmed this" and "the tool asserted it about
 * itself". A pin that does not say which one it is does not get read as the stronger one.
 */
const OPERATOR_CONFIRMED = 'operator-confirmed';

/** A pinned digest, or null when the lock does not carry a readable one. */
function readPinnedSha(lock) {
  return typeof lock?.sha256 === 'string' && SHA256.test(lock.sha256) ? lock.sha256.toLowerCase() : null;
}

/** A pinned gain, or null when the lock does not carry a readable one. */
function readPinnedGain(lock) {
  const gain = typeof lock?.musicGain === 'number' ? lock.musicGain : Number.NaN;
  return Number.isFinite(gain) ? gain : null;
}

/**
 * Decides whether this gain, for this source, has been confirmed.
 *
 * Three things must hold, and the third is the one that was missing: the source matches,
 * the gain matches, AND the pin records an actual operator confirmation. Checking only
 * the first two reads a self-pinned legacy lock as confirmed, and a successful run then
 * rewrites it carrying `evidence: "operator-confirmed"` — laundering a record into
 * provenance it never had, and producing a file that looks STRONGER than its source.
 * Putting the distinction in the artifact and not in the predicate is the same class of
 * error as the rest of this audit: it exists in the file and not in the decision.
 *
 * A lock whose fields cannot be read is NOT treated as a match either. Defaulting an
 * unreadable pin to "fine" would produce the evidence of a check with none of the
 * protection — a truncated or hand-edited lock would wave any gain through.
 *
 * @param {object|null} lock the parsed lock file, or null when there is none
 * @param {{source: string, sha256: string, musicGain: number}} current what is being applied now
 * @returns {{first: boolean, unreadablePin: boolean, unconfirmedPin: boolean,
 *            pinRecordsConfirmation: boolean, sourceChanged: boolean, gainChanged: boolean,
 *            requiresConfirmation: boolean, pinnedSha: string|null, pinnedGain: number|null}}
 */
export function classifyGainPin(lock, current) {
  const first = lock === null || lock === undefined || typeof lock !== 'object' || Array.isArray(lock);

  const pinnedSha = first ? null : readPinnedSha(lock);
  const pinnedGain = first ? null : readPinnedGain(lock);
  const unreadablePin = !first && (pinnedSha === null || pinnedGain === null);

  const sourceChanged = pinnedSha !== null && pinnedSha !== String(current.sha256).toLowerCase();
  const gainChanged = pinnedGain !== null && pinnedGain !== current.musicGain;

  // Whether the EXISTING pin was ever agreed to, asked independently of whether it is
  // stale. Staleness and provenance are different questions, and collapsing them is what
  // let a refusal describe a legacy pin as "confirmed against" — asserting an agreement
  // that never happened, inside the one feature built to stop exactly that.
  const pinRecordsConfirmation = !first && lock.evidence === OPERATOR_CONFIRMED;

  // Only asked once the pin is otherwise readable and matching: "this lock records no
  // confirmation" is the right diagnosis for a legacy pin, and the wrong one for a pin
  // that is simply stale.
  const unconfirmedPin = !first && !unreadablePin && !sourceChanged && !gainChanged
    && !pinRecordsConfirmation;

  return {
    first,
    unreadablePin,
    unconfirmedPin,
    pinRecordsConfirmation,
    sourceChanged,
    gainChanged,
    requiresConfirmation: first || unreadablePin || unconfirmedPin || sourceChanged || gainChanged,
    pinnedSha,
    pinnedGain,
  };
}

const WHY_PRESENCE_IS_NOT_LEVEL =
  'A gain is only meaningful for the track it was confirmed against; two tracks can sit\n' +
  '30 dB apart and both accept the same in-range gain. The narration-gap checks cannot\n' +
  'see this — they measure whether a bed is present, not whether it is at the right level.';

/*
 * THE MEASUREMENT COMES AFTER, AND THE INSTRUCTION HAS TO SAY SO.
 *
 * The first version of this text told the operator to measure the result with
 * check-levels.mjs and THEN re-run with --confirm-gain. That cannot be done: the result
 * it names is the mix this very run would have produced, and the refusal is what stopped
 * it being produced. The circularity was documented in the README while the text a person
 * actually reads still asked for the impossible order.
 *
 * check-levels.mjs measures a RENDERED FILE. So the honest sequence is confirm, render,
 * measure, and only then deliver — and --confirm-gain has to be described as what it is,
 * an acceptance recorded in advance, not a measurement that has already happened.
 */
const HOW_TO_PROCEED =
  'There is nothing to measure yet: the bed level can only be read off a finished mix,\n' +
  'and that mix is what this run would have produced. So the order is:\n' +
  '\n' +
  '  1. re-run with --confirm-gain — this records a PROVISIONAL acceptance of this gain\n' +
  '     for this source, and produces the mix;\n' +
  '  2. measure that output before you deliver it:\n' +
  '       node src/check-levels.mjs --file <your --out file>\n' +
  '  3. read the lead-in window, where the bed plays alone. If the level is wrong, re-run\n' +
  '     step 1 with a corrected --music-gain; the pin will ask again because the gain moved.\n' +
  '\n' +
  '--confirm-gain records that YOU accepted this gain. It does not record that anyone\n' +
  'measured the result, and this tool cannot do that for you — see the gain-pin section\n' +
  'of the README for why, and for what closing that gap properly would take.';

/**
 * The refusal text for an unconfirmed gain, naming which of the three occasions applies.
 *
 * Each branch names both sides of what it compared. "Something changed" sends the reader
 * looking; "1.5 became 3, against the same track" tells them what to check.
 */
export function describeGainPinRefusal(verdict, current) {
  const short = (sha) => String(sha).slice(0, 12);
  // How the EXISTING pin may honestly be described. A stale pin and an unconfirmed one
  // are independent, so the staleness branches below must not borrow the word "confirmed"
  // from a record that never carried it.
  const held = verdict.pinRecordsConfirmation ? 'confirmed' : 'pinned, NEVER CONFIRMED,';
  const legacyNote = verdict.pinRecordsConfirmation
    ? ''
    : '\nThe pin it is being compared against records no confirmation either — it was\n' +
      'written by the old self-pinning code. Neither the old value nor the new one has\n' +
      'been agreed to by anyone.';
  const head = (() => {
    if (verdict.first) {
      return (
        `--music-gain ${current.musicGain} has NEVER BEEN CONFIRMED for ${current.source} ` +
        `(${short(current.sha256)}).\n` +
        'There is no pin to check it against, so nothing here has established that this\n' +
        'gain is right for this track — and pinning it now would record a confirmation\n' +
        'that never happened.'
      );
    }
    if (verdict.unreadablePin) {
      return (
        'the music gain pin exists but cannot be read as a pin — its source digest or its\n' +
        'gain is missing or malformed. An unreadable pin is not a confirmation, and it is\n' +
        'not treated as one.'
      );
    }
    if (verdict.unconfirmedPin) {
      return (
        `the music gain pin matches ${current.source} (${short(current.sha256)}) at gain ` +
        `${current.musicGain}, but it RECORDS NO CONFIRMATION.\n` +
        'It was written by a version of this tool that pinned its own default without\n' +
        'asking anyone, so the values agreeing proves only that nothing has changed since\n' +
        'the tool agreed with itself. Matching a record nobody made is not evidence.\n' +
        'Re-confirming an old pin costs one flag; trusting one costs a delivered mix.'
      );
    }
    if (verdict.sourceChanged && verdict.gainChanged) {
      return (
        'BOTH the music source and --music-gain changed.\n' +
        `  ${held}  ${short(verdict.pinnedSha)} at gain ${verdict.pinnedGain}\n` +
        `  now        ${current.source} (${short(current.sha256)}) at gain ${current.musicGain}` +
        legacyNote
      );
    }
    if (verdict.sourceChanged) {
      return (
        'the music source CHANGED but --music-gain did not.\n' +
        `  ${held} against  ${short(verdict.pinnedSha)} at gain ${verdict.pinnedGain}\n` +
        `  now supplied       ${current.source} (${short(current.sha256)}) at gain ${current.musicGain}` +
        legacyNote
      );
    }
    return (
      'the music gain CHANGED against an unchanged source.\n' +
      `  ${held}  gain ${verdict.pinnedGain} for ${current.source} (${short(current.sha256)})\n` +
      `  now asked  gain ${current.musicGain} for the same track\n` +
      'Nobody has confirmed the new gain. The source not moving is not evidence about a\n' +
      'multiplier that did.' +
      legacyNote
    );
  })();

  return `${head}\n\n${WHY_PRESENCE_IS_NOT_LEVEL}\n\n${HOW_TO_PROCEED}`;
}

/**
 * The one-line pin status for the plan.
 *
 * The plan writes nothing, so it does not refuse — but it must not read as though the
 * gain were settled when --apply is going to stop. It says which way it will go.
 */
export function describeGainPinPlan(verdict, current, confirmed) {
  const short = String(current.sha256).slice(0, 12);
  if (!verdict.requiresConfirmation) return `confirmed for ${current.source} (${short}) at gain ${current.musicGain}`;
  const why = verdict.first
    ? 'never confirmed'
    : verdict.unreadablePin
      ? 'pin unreadable'
      : verdict.unconfirmedPin
        ? 'pin records no confirmation (written by the old self-pinning code)'
        : verdict.sourceChanged && verdict.gainChanged
          ? 'source and gain both changed'
          : verdict.sourceChanged
            ? 'source changed'
            : 'gain changed';
  return confirmed
    ? `${why} — will be RE-PINNED to ${short} at gain ${current.musicGain} (--confirm-gain given)`
    : `${why} — --apply will REFUSE until --confirm-gain is given`;
}
