/*
 * Audio-only remux: mixes the ambient bed under the narration and muxes it
 * back onto the ALREADY-ENCODED video stream with -c:v copy, so the video is
 * bit-identical and no re-render is needed (~1 min instead of ~27).
 *
 * Default levels are the ones approved on Part 1:
 *   voice  volume=1.14    (the encoder normalisation gain; encode-mp4 logs it)
 *   music  volume=1.50    (+3.5 dB, the "slightly louder" pass)
 *   amix   normalize=0    (do NOT let amix halve both buses)
 *   alimiter limit=0.891  (-1.0 dBFS ceiling)
 *
 * Mono -> stereo uses pan, NOT aformat: aformat applies -3 dB power
 * compensation and quietly drops the narration level.
 *
 * Output is 24 kHz stereo to match the delivered Part 1 exactly.
 *
 * Three things were wrong here and all three are load-bearing:
 *   - the input and output filenames were hardcoded to one old video;
 *   - the gains came straight off argv into an ffmpeg filter graph with no
 *     validation, where a comma does not error, it appends another filter;
 *   - ffmpeg was given -y unconditionally, and the md5 check that exists purely
 *     to prove the video stream survived printed "!! VIDEO STREAM CHANGED !!"
 *     and still exited 0 — waving through the exact case it was written to catch.
 */
import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { EXIT, CliError, runCli, requireExistingFile, resolveOutput, parseBoundedNumber } from './cli-support.mjs';
import { videoStreamVerdict } from './remux-verify.mjs';

const LOCK_NAME = 'music-gain.lock.json';

const sha256File = (f) => crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');

/**
 * A MUSIC GAIN IS ONLY MEANINGFUL FOR THE TRACK IT WAS CALIBRATED AGAINST
 * (bug-ledger entry 16).
 *
 * Bounding the gain catches a gain that is out of range. It cannot catch a gain that is
 * perfectly in range and simply wrong for the track it now applies to, which is the
 * failure that actually happened: a bed generated by make-music.mjs measured -43.1 dB
 * RMS, a licensed master measured -11.4 dB — 31.7 dB apart — and the unchanged gain
 * shipped the bed about 10 dB hot.
 *
 * Nothing downstream sees it. The narration-gap checks measure whether a bed is
 * PRESENT, not whether it is at the right LEVEL, so they stayed green. Only comparing
 * whole files against each other catches it, and by then the render is spent.
 *
 * So the check belongs here, where the SOURCE changes — not where the gain is parsed.
 * The gain is pinned to a content hash. Swap the track and the pin no longer matches,
 * and the remux refuses until the level has actually been re-checked.
 */
function assertGainMatchesSource({ projectDir, music, musicGain, values }) {
  const lockPath = path.join(projectDir, LOCK_NAME);
  const digest = sha256File(music);
  const current = { source: path.basename(music), sha256: digest, musicGain };

  let lock = null;
  if (fs.existsSync(lockPath)) {
    try {
      lock = JSON.parse(fs.readFileSync(lockPath, 'utf8'));
    } catch {
      throw new CliError(`${LOCK_NAME} is not readable JSON — delete it and re-confirm the gain`);
    }
  }

  if (lock && lock.sha256 !== digest && !values['confirm-gain']) {
    throw new CliError(
      'the music source CHANGED but --music-gain did not.\n' +
      `  calibrated against  ${lock.source} (${String(lock.sha256).slice(0, 12)}) at gain ${lock.musicGain}\n` +
      `  now supplied        ${current.source} (${digest.slice(0, 12)}) at gain ${musicGain}\n\n` +
      'A gain is only meaningful for the track it was measured against; two tracks can sit\n' +
      '30 dB apart and both accept the same in-range gain. The gap checks cannot see this —\n' +
      'they measure whether a bed is present, not whether it is at the right level.\n\n' +
      'Re-measure with check-levels.mjs, then re-run with --confirm-gain to re-pin.');
  }

  return { lockPath, current, changed: Boolean(lock) && lock.sha256 !== digest, first: !lock };
}
import { probeDurationSeconds } from './audio-probe.mjs';

// Video length from frame-capture's own frame formula, so this agrees with the encoded
// stream exactly rather than depending on a container probe. Falls back to the timeline
// duration when timing.json is unreadable — the loop only needs a target to cover.
function resolveVideoSeconds(projectDir, values) {
  if (values['video-seconds']) {
    return parseBoundedNumber(values['video-seconds'], { name: '--video-seconds', min: 0.1, max: 36000 });
  }
  const timingPath = path.join(projectDir, 'timing.json');
  const timing = JSON.parse(fs.readFileSync(timingPath, 'utf8'));
  const fps = Number(timing.project?.fps || 30);
  const durationMs = Number(timing.durationMs);
  if (!Number.isFinite(durationMs) || durationMs <= 0) {
    throw new CliError(`invalid timing.durationMs (${durationMs}) in ${timingPath}`);
  }
  return Math.ceil(((durationMs + 1000) / 1000) * fps) / fps;
}

// Linear volume multipliers. 8.0 is about +18 dB — far past anything useful here, and
// well short of a value that would produce a nonsense filter graph.
const GAIN_MIN = 0;
const GAIN_MAX = 8;

const USAGE = `
remux-music — mix the music bed under the narration and mux it onto an existing
video stream without re-encoding the video (pipeline stage S8/S9, "the cheap path").

  node remux-music.mjs --video render.mp4 --out render-with-music.mp4
                                                       plan only (default)
  node remux-music.mjs --video render.mp4 --out render-with-music.mp4 --apply
  node remux-music.mjs --video render.mp4 --out render-with-music.mp4 --apply --replace

Options
  --video <file>        the already-encoded video (required)
  --out <file>          output file (required)
  --voice <file>        narration track (default: voiceover.mp3)
  --music <file>        music bed (default: music.wav)
  --voice-gain <n>      linear voice gain, ${GAIN_MIN}..${GAIN_MAX} (default: 1.14)
  --music-gain <n>      linear music gain, ${GAIN_MIN}..${GAIN_MAX} (default: 1.50)
  --crossfade <sec>     crossfade at each loop wrap, 0.1..30 (default: 3)
  --no-loop             refuse rather than loop a music bed shorter than the video
  --confirm-gain        re-pin --music-gain to a changed music source (bug-ledger 16)
  --video-seconds <n>   override the video length used to size the loop
  --project <dir>       project root; no path may escape it (default: current directory)
  --ffmpeg <path>       ffmpeg binary (default: read from ffmpeg-path.txt in the project)
  --apply               actually remux. Without it nothing is written.
  --replace             permit overwriting an existing --out
  --help                show this message

Exit codes: 0 success/plan · 1 ffmpeg failed or the video stream was NOT preserved · 2 bad usage
`.trimStart();

await runCli(async () => {
  let values;
  try {
    ({ values } = parseArgs({
      options: {
        video: { type: 'string' },
        out: { type: 'string' },
        voice: { type: 'string' },
        music: { type: 'string' },
        'voice-gain': { type: 'string' },
        'music-gain': { type: 'string' },
        crossfade: { type: 'string' },
        'no-loop': { type: 'boolean' },
    'confirm-gain': { type: 'boolean' },
        project: { type: 'string' },
        ffmpeg: { type: 'string' },
        apply: { type: 'boolean', default: false },
        replace: { type: 'boolean', default: false },
        help: { type: 'boolean', short: 'h', default: false },
      },
      strict: true,
    }));
  } catch (err) {
    throw new CliError(`${err.message}\n\n${USAGE}`);
  }

  if (values.help) {
    console.log(USAGE);
    return EXIT.OK;
  }
  if (!values.video || !values.out) {
    throw new CliError(`--video and --out are both required\n\n${USAGE}`);
  }

  const projectDir = path.resolve(values.project ?? process.cwd());
  const video = requireExistingFile(projectDir, values.video, 'video');
  const voice = requireExistingFile(projectDir, values.voice ?? 'voiceover.mp3', 'voice track');
  const music = requireExistingFile(projectDir, values.music ?? 'music.wav', 'music bed');
  const outPath = resolveOutput(projectDir, values.out, {
    apply: values.apply === true,
    replace: values.replace === true,
    label: 'output',
  });
  if (outPath === video) {
    throw new CliError('--out must differ from --video; remuxing onto the source in place would destroy it');
  }

  // Validated before they are ever interpolated. `volume=${gain}` sits inside a filter
  // graph, so an unchecked value is a filter-injection primitive, not just a bad number.
  const voiceGain = parseBoundedNumber(values['voice-gain'] ?? '1.14', {
    name: '--voice-gain', min: GAIN_MIN, max: GAIN_MAX,
  });
  const musicGain = parseBoundedNumber(values['music-gain'] ?? '1.50', {
    name: '--music-gain', min: GAIN_MIN, max: GAIN_MAX,
  });

  // SHORT MUSIC IS LOOPED, NOT TRUNCATED (bug-ledger entry 15).
  // `amix duration=longest` describes how long the OUTPUT runs — it takes the longest
  // input. It does not loop or pad a short one, so a bed that ends early simply stops
  // contributing and the rest of the video plays with no bed at all. Nothing reports it.
  // Every earlier video was immune only because make-music.mjs generates the bed TO
  // LENGTH; the first file-sourced track hit this immediately, leaving 92 s bedless.
  //
  // Probing decodes media, so it is strict under --apply but must NOT be a precondition
  // of planning: a plan is supposed to be answerable about inputs that are absent,
  // stubbed or not yet rendered. Probing unconditionally made `remux-music` with no
  // flags exit non-zero on an undecodable stub, which breaks the plan-by-default
  // contract every other stage now honours.
  const gainPin = assertGainMatchesSource({ projectDir, music, musicGain, values });

  const xfade = parseBoundedNumber(values.crossfade ?? '3', {
    name: '--crossfade', min: 0.1, max: 30,
  });

  let musicSeconds = null;
  let videoSeconds = null;
  let undecidable = null;
  try {
    musicSeconds = await probeDurationSeconds(music);
    videoSeconds = resolveVideoSeconds(projectDir, values);
  } catch (err) {
    if (values.apply) throw err;
    undecidable = err.message;
  }

  const short = undecidable === null && musicSeconds < videoSeconds;

  if (short && values['no-loop'] === true) {
    throw new CliError(
      `music is ${musicSeconds.toFixed(2)}s but the video is ${videoSeconds.toFixed(2)}s — ` +
      `the last ${(videoSeconds - musicSeconds).toFixed(2)}s would have NO bed at all. ` +
      `Drop --no-loop to loop it with a crossfade, or supply a longer track.`);
  }
  if (short && musicSeconds <= xfade) {
    throw new CliError(
      `music (${musicSeconds.toFixed(2)}s) must be longer than the ${xfade}s crossfade to loop`);
  }

  // n copies crossfaded end-to-end yield n*D - (n-1)*X seconds. Smallest covering n.
  const copies = short ? Math.max(2, Math.ceil((videoSeconds - xfade) / (musicSeconds - xfade))) : 1;
  const trim = undecidable === null ? `atrim=0:${videoSeconds},` : '';

  let musicFilter;
  if (copies === 1) {
    musicFilter = `[2:a]${trim}asetpts=N/SR/TB,volume=${musicGain}[mu];`;
  } else {
    let prev = '2:a';
    musicFilter = '';
    for (let i = 1; i < copies; i += 1) {
      const label = `ml${i}`;
      musicFilter += `[${prev}][${i + 2}:a]acrossfade=d=${xfade}:c1=tri:c2=tri[${label}];`;
      prev = label;
    }
    musicFilter += `[${prev}]${trim}asetpts=N/SR/TB,volume=${musicGain}[mu];`;
  }

  const filter =
    `[1:a]volume=${voiceGain},pan=stereo|c0=c0|c1=c0[vo];` +
    musicFilter +
    `[vo][mu]amix=inputs=2:duration=longest:normalize=0[mx];` +
    `[mx]alimiter=limit=0.891:level=disabled[out]`;

  const musicInputs = Array.from({ length: copies }, () => ['-i', music]).flat();

  const FF = resolveFfmpeg(projectDir, values.ffmpeg);
  const ffArgs = [
    values.replace ? '-y' : '-n', '-hide_banner', '-loglevel', 'error',
    '-i', video, '-i', voice, ...musicInputs,
    '-filter_complex', filter,
    '-map', '0:v', '-c:v', 'copy',
    '-map', '[out]', '-c:a', 'aac', '-b:a', '160k', '-ar', '24000', '-ac', '2',
    '-movflags', '+faststart',
    outPath,
  ];

  if (!values.apply) {
    console.log('plan: audio-only remux (video stream copied, not re-encoded)');
    console.log(`  video   ${video}`);
    console.log(`  voice   ${voice}  (gain ${voiceGain})`);
    console.log(`  music   ${music}  (gain ${musicGain})`);
    console.log(`  gain    ${gainPin.first ? `will PIN to ${gainPin.current.sha256.slice(0, 12)} on --apply`
      : gainPin.changed ? `RE-PINNING to ${gainPin.current.sha256.slice(0, 12)} (--confirm-gain)`
        : `pinned to ${gainPin.current.sha256.slice(0, 12)} — source unchanged`}`);
    if (undecidable !== null) {
      console.log(`  loop    UNDECIDED — could not read durations (${undecidable}).`);
      console.log('          Planned WITHOUT looping. If the track is shorter than the');
      console.log('          video, --apply will loop it and this plan understates the graph.');
    } else if (copies > 1) {
      console.log(`  loop    music ${musicSeconds.toFixed(2)}s < video ${videoSeconds.toFixed(2)}s ` +
        `— ${copies} copies, ${xfade}s crossfade at each wrap`);
    } else {
      console.log(`  loop    not needed — music ${musicSeconds.toFixed(2)}s covers video ${videoSeconds.toFixed(2)}s`);
    }
    console.log(`  output  ${outPath}`);
    console.log(`  filter  ${filter}`);
    console.log(`\nwould run:\n  ${FF} ${ffArgs.join(' ')}`);
    console.log('\nnothing was written. Re-run with --apply to remux.');
    return EXIT.OK;
  }

  console.log(`voice ${voiceGain} · music ${musicGain}`);
  try {
    execFileSync(FF, ffArgs, { stdio: 'inherit' });
  } catch (err) {
    throw new CliError(`ffmpeg failed while remuxing (${err.message}) — ${outPath} was not produced`, EXIT.FAILED);
  }

  // Prove the video stream survived untouched. This check is the entire justification
  // for the cheap path: if the stream changed, the output is a re-encode wearing the
  // cheap path's name, and it must not be published as an approved deliverable.
  const md5 = (f) => execFileSync(FF, ['-hide_banner', '-loglevel', 'error', '-i', f,
    '-map', '0:v', '-c', 'copy', '-f', 'md5', '-'], { encoding: 'utf8' }).trim();

  const before = md5(video);
  const after = md5(outPath);
  console.log(`video ${before}`);
  console.log(`remux ${after}`);
  console.log(`${outPath} ${(fs.statSync(outPath).size / 1048576).toFixed(2)} MB`);

  const verdict = videoStreamVerdict(before, after, path.basename(outPath));
  if (!verdict.identical) {
    console.error(`\nFAILED: ${verdict.message}`);
    return verdict.exitCode;
  }
  console.log(verdict.message);

  // Pin only after the remux is proven good. Pinning earlier would record a gain that
  // was never actually used, and a failed run would leave the next one wrongly reassured.
  fs.writeFileSync(gainPin.lockPath,
    `${JSON.stringify({ ...gainPin.current, confirmedAt: new Date().toISOString() }, null, 2)}\n`);
  console.log(`${LOCK_NAME}: gain ${musicGain} pinned to ${gainPin.current.source} ` +
    `(${gainPin.current.sha256.slice(0, 12)})`);

  return EXIT.OK;
});

/** Resolves the ffmpeg binary, preferring --ffmpeg over the project's ffmpeg-path.txt. */
function resolveFfmpeg(projectDir, override) {
  if (override) return override;
  const pointer = path.join(projectDir, 'ffmpeg-path.txt');
  if (!fs.existsSync(pointer)) {
    throw new CliError(
      `ffmpeg-path.txt not found in ${projectDir} — create it containing the path to ffmpeg, or pass --ffmpeg <path>`,
    );
  }
  const ff = fs.readFileSync(pointer, 'utf8').trim();
  if (!ff) throw new CliError(`ffmpeg-path.txt in ${projectDir} is empty`);
  return ff;
}
