namespace Forge.EvalEngine.Transcripts;

/// <summary>
/// Where a turn's stimulus came from.
/// </summary>
/// <remarks>
/// <b>Provenance is load-bearing, not decoration.</b> An assertion evaluated against a turn whose
/// stimulus was <see cref="Synthesized"/> when the suite author believed it was
/// <see cref="Scripted"/> measures the simulated caller rather than the system under test. That
/// exact confusion produced a real misdiagnosis in the harness this design came from, which is
/// why the suite loader enforces the script-overrun guard and why this field is recorded
/// per turn rather than per run.
/// </remarks>
public enum TurnProvenance
{
    /// <summary>Replayed verbatim from the scenario's scripted answers.</summary>
    Scripted,

    /// <summary>Generated by a model standing in for the caller.</summary>
    Synthesized,

    /// <summary>Captured from a real external caller.</summary>
    Live,
}

/// <summary>
/// One exchange: a stimulus sent to the system under test and the response it returned.
/// </summary>
/// <remarks>
/// The vocabulary here is deliberately domain-neutral. It is <c>stimulus</c> and
/// <c>response</c> — never <c>question</c> and <c>answer</c> — because the moment one domain's
/// words enter the core types, the "generic" engine has quietly encoded that domain's
/// assumptions.
/// </remarks>
public sealed record Turn
{
    /// <summary>Gets the one-based position of this turn in the transcript.</summary>
    public required int Index { get; init; }

    /// <summary>Gets the input sent to the system under test.</summary>
    public required string Stimulus { get; init; }

    /// <summary>
    /// Gets what the system under test returned, or <see langword="null"/> if it returned nothing
    /// — for example when the turn failed in transport.
    /// </summary>
    public string? Response { get; init; }

    /// <summary>Gets where the stimulus came from.</summary>
    public required TurnProvenance Provenance { get; init; }

    /// <summary>Gets the wall-clock time this turn took.</summary>
    public TimeSpan Elapsed { get; init; }
}

/// <summary>
/// What the system under test ultimately did, in the form downstream stages compare against
/// <see cref="Scenarios.Grading"/>.
/// </summary>
public sealed record Outcome
{
    /// <summary>
    /// Gets the terminal outcome the system reached, compared against
    /// <see cref="Scenarios.Grading.ExpectedOutcome"/>.
    /// </summary>
    public string? ObservedOutcome { get; init; }

    /// <summary>
    /// Gets the route the system took, compared against
    /// <see cref="Scenarios.Grading.ExpectedPath"/>.
    /// </summary>
    public string? ObservedPath { get; init; }

    /// <summary>
    /// Gets the structured fields the system returned, flattened and keyed by path — for example
    /// <c>scope/confirm</c>.
    /// </summary>
    /// <remarks>
    /// The keys are the same vocabulary an <see cref="Assertions.AssertionSpec"/> parameter uses,
    /// which is why a parameter may itself contain a <c>/</c> and why the expression is split on
    /// the first colon only.
    /// </remarks>
    public IReadOnlyDictionary<string, string?> Fields { get; init; } =
        new Dictionary<string, string?>(StringComparer.Ordinal);
}

/// <summary>
/// Transport-level detail about how a run reached the system under test.
/// </summary>
/// <remarks>
/// Kind-agnostic by construction: anything specific to HTTP, MCP, or a model provider goes in
/// <see cref="Attributes"/> rather than becoming a field here. A field here would force every
/// downstream stage to know which transports exist.
/// </remarks>
public sealed record TransportMetadata
{
    /// <summary>Gets the transport identifier, for example <c>http</c> or <c>mcp</c>.</summary>
    public string? Kind { get; init; }

    /// <summary>Gets the address the run was directed at.</summary>
    public string? Endpoint { get; init; }

    /// <summary>Gets transport-specific detail that no downstream stage is required to understand.</summary>
    public IReadOnlyDictionary<string, string> Attributes { get; init; } =
        new Dictionary<string, string>(StringComparer.Ordinal);
}

/// <summary>
/// The shared spine of the engine: what happened during one run of one scenario.
/// </summary>
/// <remarks>
/// <para>
/// Every runner — REST, MCP, or LLM — produces this same type. Assertions, aggregation,
/// comparison, and reporting operate only on <see cref="Transcript"/> and <see cref="Outcome"/>,
/// and are therefore blind to which kind of scenario produced them. A REST run is a transcript
/// with one turn.
/// </para>
/// <para>
/// This record holds collections, so equality is defined by <b>canonical value</b> rather than by
/// the compiler-generated member-wise comparison, which would compare those collections by
/// reference and report two identically-valued transcripts as different.
/// </para>
/// </remarks>
public sealed record Transcript
{
    /// <summary>Gets the identifier of the scenario this transcript came from.</summary>
    public required string ScenarioId { get; init; }

    /// <summary>Gets the turns that occurred, in order.</summary>
    public IReadOnlyList<Turn> Turns { get; init; } = [];

    /// <summary>Gets what the system under test ultimately did.</summary>
    public Outcome Outcome { get; init; } = new();

    /// <summary>Gets how the run reached the system under test.</summary>
    public TransportMetadata Transport { get; init; } = new();

    /// <summary>
    /// Gets the seed this run was driven with. Stamped so the run can be reproduced exactly.
    /// </summary>
    public required long Seed { get; init; }

    /// <summary>Gets when the run started.</summary>
    public required DateTimeOffset StartedAt { get; init; }

    /// <summary>Gets the wall-clock duration of the whole run.</summary>
    public TimeSpan Duration { get; init; }

    /// <summary>Determines whether another transcript has the same canonical value.</summary>
    /// <param name="other">The transcript to compare against, or null.</param>
    /// <returns><see langword="true"/> when both serialize to identical canonical JSON.</returns>
    public bool Equals(Transcript? other) => Serialization.CanonicalJson.AreEquivalent(this, other);

    /// <summary>Returns a hash consistent with canonical-value equality.</summary>
    /// <returns>The hash of this transcript's canonical JSON.</returns>
    public override int GetHashCode() =>
        StringComparer.Ordinal.GetHashCode(Serialization.CanonicalJson.Serialize(this));
}
